### PR TITLE
Added a feature to search forward and backward

### PR DESCRIPTION
**Pull request by vick08**
Control+Command+g will search forward based on the last query. Control+Shift+Command+g will search backward based on the last query. In both cases VOCR cursor will land on the chunk that contains the term and speak the chunk.
All the searches are performed from the current location. To initiate the search, use Control+Command+f.

### CODE REVIEW

**Comment by vick08** [comment]
Added safeguards to prevent "index out of range" error when starting a search with control+command+f.

**Comment by chigkim** [comment]
Awesome! This works now without out of index error!
Here are a  few thoughts:

If the move mouse setting is on, can we move the mouse for find, find next, find previous?

If the positional audio is on, it should also play audio alert. I think if you use the same logic in `if Settings.moveMouse` in Navigation.swift, it should work. Also the convert2coordinates function will play the positional audio.

I don't think we need the phrase found VOCR in. Instead, it can just announce the result and make the announcement more concise.

Find next and find previous don't open dialog, so we can use speak instead of speakWithSynthesizer.

Thanks so much!

**Comment by vick08** [comment]
OK, added the requested changes in the last three commits.
The only ask I am not yet sure about is the VOCR message when the term is found. Since there may be several terms on the screen, I thought it may be helpful to give some context as to where they appear.
If you feel strongly about this, I am happy to simplify the "found" message. Otherwise, we can place the feature into the hands of users and see what they say. :)
What do you think?

**Comment by vick08** [comment]
K, done now!

**Comment by vick08** [comment]
Added "close" button to few dialogs.

**Pull request merged**
